import 'package:flutter/material.dart';

final List<Map<String, dynamic>> employees = [
  {
    'name': 'Darlene Robertson',
    'avatar': 'DR',
    'avatarColor': const Color(0xFFE9DAC1),
    'textColor': const Color(0xFF7D5A50),
    'id': '345321231',
    'department': 'Design',
    'designation': 'UI/UX Designer',
    'type': 'Remote',
  },
  {
    'name': 'Floyd Miles',
    'avatar': 'FM',
    'avatarColor': const Color(0xFFDAEAF1),
    'textColor': const Color(0xFF2B6777),
    'id': '987890345',
    'department': 'Development',
    'designation': 'PHP Developer',
    'type': 'Office',
  },
  {
    'name': 'Cody Fisher',
    'avatar': 'CF',
    'avatarColor': const Color(0xFFE4D0D0),
    'textColor': const Color(0xFFBE9E9E),
    'id': '453367122',
    'department': 'Sales',
    'designation': 'Sales Manager',
    'type': 'Office',
  },
  {
    'name': 'Dianne Russell',
    'avatar': 'DR',
    'avatarColor': const Color(0xFFDBDFAA),
    'textColor': const Color(0xFF5F8D4E),
    'id': '345321231',
    'department': 'Sales',
    'designation': 'BDM',
    'type': 'Remote',
  },
  {
    'name': 'Savannah Nguyen',
    'avatar': 'SN',
    'avatarColor': const Color(0xFFFFE6E6),
    'textColor': const Color(0xFFFF7BA9),
    'id': '453677881',
    'department': 'Design',
    'designation': 'Design Lead',
    'type': 'Office',
  },
  {
    'name': 'Jacob Jones',
    'avatar': 'JJ',
    'avatarColor': const Color(0xFFD1E8E2),
    'textColor': const Color(0xFF408E91),
    'id': '009918765',
    'department': 'Development',
    'designation': 'Python Developer',
    'type': 'Remote',
  },
  {
    'name': 'Marvin McKinney',
    'avatar': 'MM',
    'avatarColor': const Color(0xFFDBE2EF),
    'textColor': const Color(0xFF3F72AF),
    'id': '238870122',
    'department': 'Development',
    'designation': 'Sr. UI Developer',
    'type': 'Remote',
  },
  {
    'name': 'Brooklyn Simmons',
    'avatar': 'BS',
    'avatarColor': const Color(0xFFFFD4D4),
    'textColor': const Color(0xFFAB3428),
    'id': '124335111',
    'department': 'PM',
    'designation': 'Project Manager',
    'type': 'Office',
  },
  {
    'name': 'Kristin Watson',
    'avatar': 'KW',
    'avatarColor': const Color(0xFFFFE9AE),
    'textColor': const Color(0xFFB99B6B),
    'id': '435540099',
    'department': 'HR',
    'designation': 'HR Executive',
    'type': 'Office',
  },
  {
    'name': 'Kathryn Murphy',
    'avatar': 'KM',
    'avatarColor': const Color(0xFFD0B8A8),
    'textColor': const Color(0xFF85586F),
    'id': '009812890',
    'department': 'Development',
    'designation': 'React JS Developer',
    'type': 'Office',
  },
  {
    'name': 'Arlene McCoy',
    'avatar': 'AM',
    'avatarColor': const Color(0xFFE3F4F4),
    'textColor': const Color(0xFF537188),
    'id': '671190345',
    'department': 'Development',
    'designation': 'Node JS',
    'type': 'Office',
  },
  {
    'name': 'Devon Lane',
    'avatar': 'DL',
    'avatarColor': const Color(0xFFF7E8F6),
    'textColor': const Color(0xFF8879B0),
    'id': '091233412',
    'department': 'BA',
    'designation': 'Business Analyst',
    'type': 'Remote',
  },
];